### ISSUE TITLE
Add this code in bot.py to make this repo 4gb. And make some changes in other files also.

### ISSUE THREAD

**Issue by vpcreatz** [TEAM-PYRO-BOTZ/PYRO-RENAME-BOT#26]
if STRING:
    apps = [Client2,bot]
    for app in apps:
        app.start()
    idle()
    for app in apps:
        app.stop()
    
else:
    bot.run()

**Comment by MrMKN** [comment]
Sorry 🙏

**Comment by MrMKN** [comment]
This is simple bot 🙏 4 is premium requested 🥲
